jwt:
  secret:
    key: HVEZfRWOe1CvPtvBa06nfUsiSecZT/zUf7TR/V0NHHtYK2VFZ7MfF6pmiF9NA4l1jFnqplVq1WjvdvpA9DUHSBi5Ag2lN/UNnuJ9DegvIsRupuMjR+Od8BTfDUKWuAOmH3RPbgvCf2crHSLeChMaLFX/9CTJ49Mmq41yTZJWRwtBwXsWPevyCwDAtXPvAlsIxTaXNVwOCZg8UOtHSzfzXDYN4hiSZ0FYZQk3a0lxFZ9V3gfUWDm9xCouYUlRzfBXGQuXCUXudlZ5waU9BlIHNR9IQ/ndgaFG2CtSCQXlsL+hFXKEVkhe3dHR2/RAj4eP3Lrh/MgEgof+ExYFf3+iAg==
