spring:
  config:
    activate:
      on-profile: develop
auction:
  datasource:
    master:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url:
        username:
        password:
        auto-commit: false
        minimum-idle: 1
        maximum-pool-size: 3
        pool-name: master-pool
        max-lifetime: 30000
    slave:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url:
        username:
        password:
        auto-commit: false
        minimum-idle: 1
        maximum-pool-size: 3
        pool-name: slave-pool
        max-lifetime: 30000
---