spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
---
spring:
  config:
    activate:
      on-profile: develop
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
---